# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2301c9dab74d2727b60538360f718ce5ba872b9cbe1cd7da207872318c78ad1b5230433c1fe5e3df59454ed2d5a1ae825949520146ad700fbb5fa890411b8c4d

test:
  secret_key_base: 8d5261ea277069ef04cdeb992dd8535f01e5068d4661de1373b8adc2412b5507343624ccf7029361cae0723ce3de8ecc2f0507c12dc2b034395bb2f71939ac81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
